#!/usr/bin/env python3
#
# (c) Stephen Bates, Huawei, 2023
#
# compstore-sql.py
# ----------------
#
# This script loads in a database from a parquet file and then
# executes an SQL query against this dataset. We use this as part of
# Stephen's PM+CS Summit presentation in April 2023. 

import pandas as pd
import duckdb
import argparse

DESC = "A program to perform SQL queries on a database that is stored " \
    "in a parquet file"

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=DESC)
    parser.add_argument("-i", dest="input", required=True,
                        help="input parquet file", metavar="FILE")
    args = parser.parse_args()

    df = pd.read_parquet(args.input)
    print(duckdb.query("SELECT * FROM df WHERE high = (SELECT max(high) FROM df)").to_df())
